# Generated by Django 4.2.9 on 2025-03-06 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Procurement_Plaform', models.CharField(max_length=50)),
                ('Product_name', models.CharField(max_length=50)),
                ('Employ_ID', models.CharField(max_length=100)),
                ('THD_Dept', models.CharField(max_length=15)),
                ('Unit_Price', models.CharField(max_length=100)),
                ('Purchasing_Links', models.CharField(max_length=50)),
                ('Product_Category', models.CharField(max_length=50)),
                ('Qty_Available', models.CharField(max_length=10)),
            ],
        ),
    ]
